
import openai
import telebot

openai.api_key = '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'
bot = telebot.TeleBot('5969023795:AAE9TJkrAAngXMBGHQISCE55oztfSaWM7dQ')
@bot.message_handler(func=lambda _: True)
def handle_message(message):
  response = openai.Completion.create(
    model="text-davinci-003",
    prompt=message.text,
    temperature=0.5,
    max_tokens=2000,
    top_p=1.0,
    frequency_penalty=0.5,
    presence_penalty=0.0,
  )
  bot.send_message(chat_id=message.from_user.id,text=response ['choices'][0]['text'])

bot.polling()
